version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: blackteatherapy-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=blackstar2024
      - WEBHOOK_URL=https://your-domain.com/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows:ro

volumes:
  n8n_data:
